# Override the amount of players that can be logged in at the same time.
# The friend server is capped at 2000 seperately.
# World has several hard coded caps of 2048.
# It's possible to go higher by changing those values in the code.
# But don't expect smooth operations.
# Default: 2000
maxConnected=2000

# Number of bot accounts. Real players can't login if it's full.
# So it should be lowered if multiple clients want to login at the same time.
# Enough tasks need to be available before they can all login.
# Default: 1999
numBots=1999

# If set to false, bots only change name when creating a new character.
# Names are taken directly from botnames_sample.zip without extracting.
# The full zip botnames.zip takes priority if you download it.
# It's split in 1000 files of which one is randomly selected on server start.
# This keeps the memory usage low with different names every time.
# You can override it by creating a botnames.txt with one name per line.
# Default: true
renameBots=true

# Percentage of bots that will reach max level if the server runs long enough.
# The remaining bots will give up at varying total levels.
# They delete their save and get replaced by a new bot.
# At 0, only one bot can reach max level but will then delete the account.
# At 100, bots never start over even when they are all max level.
# Default: 10
percentMax=10

# Comma seperated usernames for which the player can see the bots in action.
# When you login with these, the bot will take control of the character.
# Make sure to logout properly for the bot to go offline until you login again.
# Otherwise the bot stays active until server restart.
# These bots are not part of `numBots`, won't get renamed or deleted.
# Default: bot,bot2,bot3,bot4
botClients=bot,bot2,bot3,bot4
